"""Render the chapter tables and the book table of contents from `chapters.yml`.

Every place that lists the chapters is generated here: the two READMEs and the two
home pages each carry a marked block, and `book/_toc.yml` is generated whole.
Titles therefore have one wording, and a new chapter is registered once.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

from chapters import LANGUAGES, Chapter, load_chapters  # noqa: E402
from paths import BOOK, REPO_ROOT  # noqa: E402

BEGIN = "<!-- chapters:begin -->"
END = "<!-- chapters:end -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

TABLE_HEAD = {
    "zh": "| # | 章节 | 正文 | 实验 | 运行 |",
    "en": "| # | Chapter | Text | Experiments | Run |",
}
TABLE_RULE = "| --- | --- | --- | --- | --- |"

# The home page is a page of the site, so it links by site path; the README is
# rendered by GitHub, so it links the checked-in PDF and points at the site for
# the saved experiment output.
KINDS = {
    "readme": {
        "zh": REPO_ROOT / "README.md",
        "en": REPO_ROOT / "README-en.md",
    },
    "home": {
        "zh": BOOK / "index.md",
        "en": BOOK / "index-en.md",
    },
}

DEMO = {"zh": ("demo", "最小演示"), "en": ("demo-en", "Minimum demo")}
TEXT_PAGE = {
    "zh": ("offline-rl-text", "离线强化学习正文（PDF）"),
    "en": ("offline-rl-text-en", "Offline RL chapter (PDF)"),
}
ATLAS = {"zh": ("failure-atlas", "RL 失败模式图鉴"), "en": ("failure-atlas-en", "Failure Atlas")}
PART_CAPTION = {"zh": "中文版", "en": "English"}
# Jupyter Book allows one root page, and it is the Chinese home (`index`). The
# English home is a page of its own part instead, listed first.
ROOT_PAGE = "index"
HOME = {"en": ("index-en", "Home")}


def _table_row(chapter: Chapter, language: str, kind: str) -> str:
    title = chapter.title[language]
    colab = f"[Colab]({chapter.colab_url(language)})"
    if kind == "readme":
        text = f"[PDF](book/{chapter.pdf(language).relative_to(BOOK).as_posix()})"
        experiments = f"[Notebook](https://powfu-zwx.github.io/BreakRL/{chapter.site_stem(language)}.html)"
    else:
        text = f"[PDF]({chapter.site_stem(language)}.pdf)"
        experiments = f"[Notebook]({chapter.site_stem(language)}.ipynb)"
    return f"| {chapter.number} | {title} | {text} | {experiments} | {colab} |"


def render_table(chapters: list[Chapter], language: str, kind: str) -> str:
    rows = [_table_row(chapter, language, kind) for chapter in chapters]
    return "\n".join([BEGIN, TABLE_HEAD[language], TABLE_RULE, *rows, END])


def _write_block(path: Path, table: str) -> bool:
    text = path.read_text(encoding="utf-8")
    if not BLOCK.search(text):
        raise ValueError(f"{path.relative_to(REPO_ROOT)}: missing {BEGIN} … {END} block")
    updated = BLOCK.sub(lambda _: table, text)
    if updated == text:
        return False
    path.write_text(updated, encoding="utf-8", newline="\n")
    return True


def render_toc(chapters: list[Chapter]) -> str:
    parts = []
    for language in LANGUAGES:
        entries = [DEMO[language]]
        if language in HOME:
            entries.insert(0, HOME[language])
        entries += [(chapter.site_stem(language), chapter.title[language]) for chapter in chapters]
        entries += [TEXT_PAGE[language], ATLAS[language]]
        lines = [f'  - caption: "{PART_CAPTION[language]}"', "    chapters:"]
        lines += [
            f"      - file: {file}\n        title: {title!r}"
            for file, title in entries
            if file != ROOT_PAGE
        ]
        parts.append("\n".join(lines))
    header = (
        "# Generated by tools/sync_pages.py from book/chapters.yml. Do not edit by hand.\n"
        "format: jb-book\n"
        f"root: {ROOT_PAGE}\n"
        "parts:\n"
    )
    return header + "\n".join(parts) + "\n"


def sync() -> list[str]:
    chapters = load_chapters()
    changed = []
    for kind, per_language in KINDS.items():
        for language, path in per_language.items():
            if _write_block(path, render_table(chapters, language, kind)):
                changed.append(path.relative_to(REPO_ROOT).as_posix())
    toc = BOOK / "_toc.yml"
    rendered = render_toc(chapters)
    if toc.read_text(encoding="utf-8") != rendered:
        toc.write_text(rendered, encoding="utf-8", newline="\n")
        changed.append(toc.relative_to(REPO_ROOT).as_posix())
    return changed


def main() -> int:
    changed = sync()
    for path in changed:
        print(f"updated: {path}")
    print(f"chapter tables and table of contents in sync ({len(changed)} file(s) written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
